# Generated by Django 5.2.6 on 2025-10-02 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doan',
            fields=[
                ('madoan', models.AutoField(db_column='MaDoAn', primary_key=True, serialize=False)),
                ('tendoan', models.CharField(db_column='TenDoAn', max_length=200)),
                ('mota', models.TextField(blank=True, db_column='MoTa', null=True)),
                ('trangthai', models.CharField(blank=True, db_column='TrangThai', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Doan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Giangvien',
            fields=[
                ('magv', models.AutoField(db_column='MaGV', primary_key=True, serialize=False)),
                ('hoten', models.CharField(blank=True, db_column='HoTen', max_length=100, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('sdt', models.CharField(blank=True, db_column='SDT', max_length=15, null=True)),
            ],
            options={
                'db_table': 'Giangvien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hocvien',
            fields=[
                ('mahv', models.AutoField(db_column='MaHV', primary_key=True, serialize=False)),
                ('hoten', models.CharField(blank=True, db_column='HoTen', max_length=100, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('sdt', models.CharField(blank=True, db_column='SDT', max_length=15, null=True)),
            ],
            options={
                'db_table': 'Hocvien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiendo',
            fields=[
                ('matiend', models.AutoField(db_column='MaTienDo', primary_key=True, serialize=False)),
                ('noidung', models.TextField(blank=True, db_column='NoiDung', null=True)),
                ('ngaycapnhat', models.DateTimeField(auto_now_add=True, db_column='NgayCapNhat')),
                ('file', models.FileField(blank=True, db_column='File', null=True, upload_to='baocao/')),
            ],
            options={
                'db_table': 'Tiendo',
                'managed': False,
            },
        ),
    ]
