# Generated by Django 5.2.6 on 2025-09-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bienban',
            fields=[
                ('mabb', models.IntegerField(db_column='MaBB', primary_key=True, serialize=False)),
                ('ngaybaove', models.DateField(blank=True, db_column='NgayBaoVe', null=True)),
                ('diadiem', models.CharField(blank=True, db_column='DiaDiem', max_length=100, null=True)),
                ('noidung', models.TextField(blank=True, db_column='NoiDung', null=True)),
                ('ghichu', models.TextField(blank=True, db_column='GhiChu', null=True)),
                ('ngaylap', models.DateField(blank=True, db_column='NgayLap', null=True)),
            ],
            options={
                'db_table': 'BIENBAN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dangky',
            fields=[
                ('madk', models.IntegerField(db_column='MaDK', primary_key=True, serialize=False)),
                ('ngaydk', models.DateField(blank=True, db_column='NgayDK', null=True)),
                ('trangthai', models.CharField(blank=True, db_column='TrangThai', max_length=50, null=True)),
            ],
            options={
                'db_table': 'DANGKY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Diemthanhvien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem', models.FloatField(blank=True, db_column='Diem', null=True)),
            ],
            options={
                'db_table': 'DIEMTHANHVIEN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doan',
            fields=[
                ('mada', models.IntegerField(db_column='MaDA', primary_key=True, serialize=False)),
                ('tenda', models.CharField(blank=True, db_column='TenDA', max_length=200, null=True)),
                ('trangthai', models.CharField(blank=True, db_column='TrangThai', max_length=50, null=True)),
                ('soluongtoida', models.IntegerField(blank=True, db_column='SoLuongToiDa', null=True)),
                ('ngaygui', models.DateField(blank=True, db_column='NgayGui', null=True)),
                ('mota', models.TextField(blank=True, db_column='MoTa', null=True)),
                ('linhvuc', models.CharField(blank=True, db_column='LinhVuc', max_length=100, null=True)),
                ('ngaybd', models.DateField(blank=True, db_column='NgayBD', null=True)),
                ('ngaykt', models.DateField(blank=True, db_column='NgayKT', null=True)),
            ],
            options={
                'db_table': 'DOAN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Giangvien',
            fields=[
                ('magv', models.IntegerField(db_column='MaGV', primary_key=True, serialize=False)),
                ('hoten', models.CharField(blank=True, db_column='HoTen', max_length=100, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('sodienthoai', models.CharField(blank=True, db_column='SoDienThoai', max_length=20, null=True)),
                ('donvicongtac', models.CharField(blank=True, db_column='DonViCongTac', max_length=100, null=True)),
            ],
            options={
                'db_table': 'GIANGVIEN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hocvien',
            fields=[
                ('mahv', models.IntegerField(db_column='MaHV', primary_key=True, serialize=False)),
                ('hoten', models.CharField(blank=True, db_column='HoTen', max_length=100, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('sodienthoai', models.CharField(blank=True, db_column='SoDienThoai', max_length=20, null=True)),
                ('lop', models.CharField(blank=True, db_column='Lop', max_length=50, null=True)),
            ],
            options={
                'db_table': 'HOCVIEN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hoidong',
            fields=[
                ('mahd', models.IntegerField(db_column='MaHD', primary_key=True, serialize=False)),
                ('tenhd', models.CharField(blank=True, db_column='TenHD', max_length=100, null=True)),
                ('ngaythanhlap', models.DateField(blank=True, db_column='NgayThanhLap', null=True)),
                ('ngayketthuc', models.DateField(blank=True, db_column='NgayKetThuc', null=True)),
                ('linhvuc', models.CharField(blank=True, db_column='LinhVuc', max_length=100, null=True)),
            ],
            options={
                'db_table': 'HOIDONG',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Huongdandoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaitro', models.CharField(blank=True, db_column='VaiTro', max_length=50, null=True)),
            ],
            options={
                'db_table': 'HUONGDANDOAN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ketquabaove',
            fields=[
                ('makq', models.IntegerField(db_column='MaKQ', primary_key=True, serialize=False)),
                ('diem', models.FloatField(blank=True, db_column='Diem', null=True)),
                ('danhgia', models.CharField(blank=True, db_column='DanhGia', max_length=200, null=True)),
                ('xeploai', models.CharField(blank=True, db_column='XepLoai', max_length=50, null=True)),
            ],
            options={
                'db_table': 'KETQUABAOVE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Thanhvienhoidong',
            fields=[
                ('matv', models.IntegerField(db_column='MaTV', primary_key=True, serialize=False)),
                ('vaitro', models.CharField(blank=True, db_column='VaiTro', max_length=50, null=True)),
            ],
            options={
                'db_table': 'THANHVIENHOIDONG',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiendo',
            fields=[
                ('matd', models.IntegerField(db_column='MaTD', primary_key=True, serialize=False)),
                ('motacongviec', models.TextField(blank=True, db_column='MoTaCongViec', null=True)),
                ('tiendophantram', models.IntegerField(blank=True, db_column='TienDoPhanTram', null=True)),
                ('ngaycapnhat', models.DateField(blank=True, db_column='NgayCapNhat', null=True)),
                ('nguoikiemtra', models.CharField(blank=True, db_column='NguoiKiemTra', max_length=100, null=True)),
            ],
            options={
                'db_table': 'TIENDO',
                'managed': False,
            },
        ),
    ]
