# Generated by Django 5.2.6 on 2025-11-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Namhoc',
            fields=[
                ('manamhoc', models.AutoField(db_column='MaNamHoc', primary_key=True, serialize=False)),
                ('namhoc', models.IntegerField(blank=True, db_column='NamHoc', null=True)),
                ('handk', models.DateField(blank=True, db_column='HanDangKy', null=True)),
            ],
            options={
                'db_table': 'NAMHOC',
                'managed': False,
            },
        ),
    ]
