# Generated by Django 5.2.6 on 2025-10-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Giangvien',
            fields=[
                ('magv', models.AutoField(db_column='MaGV', primary_key=True, serialize=False)),
                ('hoten', models.CharField(blank=True, db_column='HoTen', max_length=100, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('sodienthoai', models.CharField(blank=True, db_column='SoDienThoai', max_length=20, null=True)),
                ('donvicongtac', models.CharField(blank=True, db_column='DonViCongTac', max_length=100, null=True)),
            ],
            options={
                'db_table': 'GIANGVIEN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hocvien',
            fields=[
                ('mahv', models.AutoField(db_column='MaHV', primary_key=True, serialize=False)),
                ('hoten', models.CharField(blank=True, db_column='HoTen', max_length=100, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('sodienthoai', models.CharField(blank=True, db_column='SoDienThoai', max_length=20, null=True)),
                ('lop', models.CharField(blank=True, db_column='Lop', max_length=50, null=True)),
            ],
            options={
                'db_table': 'HOCVIEN',
                'managed': False,
            },
        ),
    ]
